[
  {
    "firstName": "Alice",
    "lastName": "Johnson",
    "Age": 28,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Peanuts",
    "currrent medications": "None",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Brian",
    "lastName": "Smith",
    "Age": 35,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "rarely",
    "chronic diseases": "Hypertension",
    "allergies": "None",
    "currrent medications": "Lisinopril",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Carla",
    "lastName": "Brown",
    "Age": 42,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "Asthma",
    "allergies": "Dust",
    "currrent medications": "Inhaler",
    "Family medical history": "Asthma"
  },
  {
    "firstName": "David",
    "lastName": "Williams",
    "Age": 50,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "never",
    "chronic diseases": "Diabetes",
    "allergies": "Penicillin",
    "currrent medications": "Metformin",
    "Family medical history": "Diabetes, Heart Disease"
  },
  {
    "firstName": "Emma",
    "lastName": "Davis",
    "Age": 30,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "None",
    "currrent medications": "None",
    "Family medical history": "Hypertension"
  },
  {
    "firstName": "Frank",
    "lastName": "Miller",
    "Age": 45,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "rarely",
    "chronic diseases": "Heart Disease",
    "allergies": "Shellfish",
    "currrent medications": "Aspirin",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Grace",
    "lastName": "Wilson",
    "Age": 27,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Pollen",
    "currrent medications": "None",
    "Family medical history": "Asthma"
  },
  {
    "firstName": "Henry",
    "lastName": "Moore",
    "Age": 38,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "several times a week",
    "chronic diseases": "High Cholesterol",
    "allergies": "None",
    "currrent medications": "Statins",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Isabella",
    "lastName": "Taylor",
    "Age": 33,
    "Gender": "Female",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Migraine",
    "allergies": "None",
    "currrent medications": "Painkillers",
    "Family medical history": "Migraine"
  },
  {
    "firstName": "Jack",
    "lastName": "Anderson",
    "Age": 29,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Latex",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Karen",
    "lastName": "Thomas",
    "Age": 41,
    "Gender": "Female",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "Arthritis",
    "allergies": "None",
    "currrent medications": "Anti-inflammatory",
    "Family medical history": "Arthritis"
  },
  {
    "firstName": "Leo",
    "lastName": "Jackson",
    "Age": 36,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Peanuts",
    "currrent medications": "None",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Mia",
    "lastName": "White",
    "Age": 26,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Gluten",
    "currrent medications": "None",
    "Family medical history": "Celiac Disease"
  },
  {
    "firstName": "Nathan",
    "lastName": "Harris",
    "Age": 48,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "rarely",
    "chronic diseases": "Hypertension",
    "allergies": "None",
    "currrent medications": "Beta Blockers",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Olivia",
    "lastName": "Martin",
    "Age": 31,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "None",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Paul",
    "lastName": "Lee",
    "Age": 39,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Diabetes",
    "allergies": "None",
    "currrent medications": "Insulin",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Quinn",
    "lastName": "Perez",
    "Age": 24,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Seafood",
    "currrent medications": "None",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Ryan",
    "lastName": "Robinson",
    "Age": 44,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "High Cholesterol",
    "allergies": "None",
    "currrent medications": "Statins",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Sophia",
    "lastName": "Clark",
    "Age": 37,
    "Gender": "Female",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Migraine",
    "allergies": "None",
    "currrent medications": "Painkillers",
    "Family medical history": "Migraine"
  },
  {
    "firstName": "Thomas",
    "lastName": "Lewis",
    "Age": 32,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Pollen",
    "currrent medications": "None",
    "Family medical history": "Asthma"
  },
  {
    "firstName": "Uma",
    "lastName": "Walker",
    "Age": 29,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Dust",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Victor",
    "lastName": "Hall",
    "Age": 46,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "rarely",
    "chronic diseases": "Heart Disease",
    "allergies": "Shellfish",
    "currrent medications": "Aspirin",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Wendy",
    "lastName": "Allen",
    "Age": 34,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Peanuts",
    "currrent medications": "None",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Xander",
    "lastName": "Young",
    "Age": 40,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Diabetes",
    "allergies": "None",
    "currrent medications": "Metformin",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Yara",
    "lastName": "Hernandez",
    "Age": 28,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Gluten",
    "currrent medications": "None",
    "Family medical history": "Celiac Disease"
  },
  {
    "firstName": "Zach",
    "lastName": "King",
    "Age": 52,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "Hypertension",
    "allergies": "None",
    "currrent medications": "Beta Blockers",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Amy",
    "lastName": "Wright",
    "Age": 31,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "None",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Blake",
    "lastName": "Lopez",
    "Age": 36,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Diabetes",
    "allergies": "None",
    "currrent medications": "Insulin",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Clara",
    "lastName": "Hill",
    "Age": 27,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Seafood",
    "currrent medications": "None",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Derek",
    "lastName": "Scott",
    "Age": 43,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "High Cholesterol",
    "allergies": "None",
    "currrent medications": "Statins",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Ella",
    "lastName": "Green",
    "Age": 38,
    "Gender": "Female",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Migraine",
    "allergies": "None",
    "currrent medications": "Painkillers",
    "Family medical history": "Migraine"
  },
  {
    "firstName": "Felix",
    "lastName": "Adams",
    "Age": 32,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Pollen",
    "currrent medications": "None",
    "Family medical history": "Asthma"
  },
  {
    "firstName": "Gina",
    "lastName": "Baker",
    "Age": 29,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Dust",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Harry",
    "lastName": "Nelson",
    "Age": 47,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "rarely",
    "chronic diseases": "Heart Disease",
    "allergies": "Shellfish",
    "currrent medications": "Aspirin",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Ivy",
    "lastName": "Carter",
    "Age": 35,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Peanuts",
    "currrent medications": "None",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Jason",
    "lastName": "Mitchell",
    "Age": 41,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Diabetes",
    "allergies": "None",
    "currrent medications": "Metformin",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Kelly",
    "lastName": "Perez",
    "Age": 28,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Gluten",
    "currrent medications": "None",
    "Family medical history": "Celiac Disease"
  },
  {
    "firstName": "Liam",
    "lastName": "Roberts",
    "Age": 53,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "Hypertension",
    "allergies": "None",
    "currrent medications": "Beta Blockers",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Maya",
    "lastName": "Turner",
    "Age": 31,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "None",
    "currrent medications": "None",
    "Family medical history": "None"
  },
  {
    "firstName": "Noah",
    "lastName": "Phillips",
    "Age": 36,
    "Gender": "Male",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Diabetes",
    "allergies": "None",
    "currrent medications": "Insulin",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Olga",
    "lastName": "Campbell",
    "Age": 27,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Seafood",
    "currrent medications": "None",
    "Family medical history": "Heart Disease"
  },
  {
    "firstName": "Peter",
    "lastName": "Parker",
    "Age": 44,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "Yes",
    "Execises": "never",
    "chronic diseases": "High Cholesterol",
    "allergies": "None",
    "currrent medications": "Statins",
    "Family medical history": "Diabetes"
  },
  {
    "firstName": "Quincy",
    "lastName": "Evans",
    "Age": 38,
    "Gender": "Female",
    "isSmoker": "Yes",
    "isDrunkard": "No",
    "Execises": "rarely",
    "chronic diseases": "Migraine",
    "allergies": "None",
    "currrent medications": "Painkillers",
    "Family medical history": "Migraine"
  },
  {
    "firstName": "Robert",
    "lastName": "Edwards",
    "Age": 32,
    "Gender": "Male",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "several times a week",
    "chronic diseases": "None",
    "allergies": "Pollen",
    "currrent medications": "None",
    "Family medical history": "Asthma"
  },
  {
    "firstName": "Sara",
    "lastName": "Collins",
    "Age": 29,
    "Gender": "Female",
    "isSmoker": "No",
    "isDrunkard": "No",
    "Execises": "daily",
    "chronic diseases": "None",
    "allergies": "Dust",
    "currrent medications": "None",
    "Family medical history": "None"
  }
]